"""Add 'Insumos' module

Revision ID: 23b7473d6881
Revises: 3c0f08543269
Create Date: 2026-04-02 17:46:38.853506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23b7473d6881'
down_revision = '3c0f08543269'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('UNIDAD_MEDIDA',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('abreviatura', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    
    unidad_table = sa.table('UNIDAD_MEDIDA',
        sa.column('nombre', sa.String),
        sa.column('abreviatura', sa.String)
    )
    op.bulk_insert(unidad_table, [
        {'nombre': 'Kilogramo', 'abreviatura': 'kg'},
        {'nombre': 'Gramo', 'abreviatura': 'g'},
        {'nombre': 'Litro', 'abreviatura': 'L'},
        {'nombre': 'Mililitro', 'abreviatura': 'ml'},
        {'nombre': 'Unidad', 'abreviatura': 'u'},
        {'nombre': 'Cartón', 'abreviatura': 'cart'},
        {'nombre': 'Onza', 'abreviatura': 'oz'}
    ])
    op.create_table('INSUMO',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_insumo', sa.String(length=100), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=True),
    sa.Column('stock_actual', sa.Float(), nullable=True),
    sa.Column('stock_minimo_alerta', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('unidad_base_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['unidad_base_id'], ['UNIDAD_MEDIDA.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('CONVERSION_UNIDAD',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('factor_conversion', sa.Float(), nullable=True),
    sa.Column('insumo_id', sa.Integer(), nullable=True),
    sa.Column('unidad_destino_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['insumo_id'], ['INSUMO.id'], ),
    sa.ForeignKeyConstraint(['unidad_destino_id'], ['UNIDAD_MEDIDA.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('CONVERSION_UNIDAD')
    op.drop_table('INSUMO')
    
    # Remove the pre-inserted generic units
    op.execute("DELETE FROM UNIDAD_MEDIDA WHERE abreviatura IN ('kg', 'g', 'L', 'ml', 'u', 'cart', 'oz')")
    
    op.drop_table('UNIDAD_MEDIDA')
    # ### end Alembic commands ###
