"""add 'Delete unused field

Revision ID: 245061dca694
Revises: 630298a45dca
Create Date: 2026-04-04 16:26:33.499753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '245061dca694'
down_revision = '630298a45dca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venta', schema=None) as batch_op:
        batch_op.drop_column('notas_internas')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notas_internas', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###
