"""Add users table

Revision ID: 36e919015e64
Revises: 
Create Date: 2026-03-24 23:08:07.748754

"""
from alembic import op
import sqlalchemy as sa
from werkzeug.security import generate_password_hash


# revision identifiers, used by Alembic.
revision = '36e919015e64'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_completo', sa.String(length=150), nullable=True),
    sa.Column('correo_electronico', sa.String(length=150), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.Column('rol_asignado', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correo_electronico')
    )
    user_table = sa.table(
        'user',
        sa.column('nombre_completo', sa.String(length=150)),
        sa.column('correo_electronico', sa.String(length=150)),
        sa.column('password', sa.String(length=100)),
        sa.column('rol_asignado', sa.String(length=50)),
    )
    op.bulk_insert(
        user_table,
        [
            {
                'nombre_completo': 'admin',
                'correo_electronico': 'admin@maison-glace.com',
                'password': generate_password_hash('admin'),
                'rol_asignado': 'admin',
            }
        ],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    user_table = sa.table(
        'user',
        sa.column('correo_electronico', sa.String(length=150)),
    )
    op.execute(
        user_table.delete().where(
            user_table.c.correo_electronico == 'admin@maison-glace.com'
        )
    )
    op.drop_table('user')
    # ### end Alembic commands ###
