"""Add 'is_active' column to Supplier and Purchase models

Revision ID: 411826fb2a23
Revises: 9c4646dcbc29
Create Date: 2026-04-10 14:50:00.248458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '411826fb2a23'
down_revision = '9c4646dcbc29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False, server_default='1'))

    with op.batch_alter_table('supplier', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False, server_default='1'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supplier', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    with op.batch_alter_table('purchase', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
