"""add 'Pedidos Personalizados' module

Revision ID: 630298a45dca
Revises: dc097bf02ae7
Create Date: 2026-04-04 16:17:53.227631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '630298a45dca'
down_revision = 'dc097bf02ae7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('detalle_venta_id', sa.Integer(), nullable=False),
    sa.Column('tipo_evento', sa.String(length=50), nullable=False),
    sa.Column('instrucciones_decoracion', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['detalle_venta_id'], ['detalle_venta.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('detalle_venta_id')
    )
    with op.batch_alter_table('venta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lugar_entrega', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('fecha_hora_entrega', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('estado', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('notas_internas', sa.Text(), nullable=True))
        batch_op.create_index(batch_op.f('ix_venta_estado'), ['estado'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venta', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_venta_estado'))
        batch_op.drop_column('notas_internas')
        batch_op.drop_column('estado')
        batch_op.drop_column('fecha_hora_entrega')
        batch_op.drop_column('lugar_entrega')

    op.drop_table('custom_order')
    # ### end Alembic commands ###
