"""add isActive column to ProductionTask table

Revision ID: 6ac178b1f932
Revises: 98d9fdba92e1
Create Date: 2026-04-04 13:00:12.071819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ac178b1f932'
down_revision = '98d9fdba92e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('production_task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('production_task', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
