"""add 'Provedores' module

Revision ID: 76a7ea3badc6
Revises: 245061dca694
Create Date: 2026-04-05 22:40:52.731359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76a7ea3badc6'
down_revision = '245061dca694'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supplier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_empresa', sa.String(length=100), nullable=False),
    sa.Column('categoria_insumos', sa.String(length=50), nullable=False),
    sa.Column('nombre_contacto', sa.String(length=100), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=False),
    sa.Column('correo_electronico', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('supplier')
    # ### end Alembic commands ###
