"""Add address and notes to Supplier

Revision ID: 9226064a457a
Revises: 76a7ea3badc6
Create Date: 2026-04-05 22:52:27.394430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9226064a457a'
down_revision = '76a7ea3badc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supplier', schema=None) as batch_op:
        batch_op.add_column(sa.Column('direccion_fisica', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('notas_adicionales', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supplier', schema=None) as batch_op:
        batch_op.drop_column('notas_adicionales')
        batch_op.drop_column('direccion_fisica')

    # ### end Alembic commands ###
