"""Add customers table

Revision ID: 9731ab3ab123
Revises: 36e919015e64
Create Date: 2026-03-25 23:10:22.443028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9731ab3ab123'
down_revision = '36e919015e64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('direccion_despacho', sa.String(length=200), nullable=True),
    sa.Column('puntos_acumulados', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_user_id'), ['user_id'], unique=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('nombre_completo',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
        batch_op.alter_column('correo_electronico',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               nullable=False)
        batch_op.alter_column('rol_asignado',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_user_correo_electronico'), ['correo_electronico'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_rol_asignado'), ['rol_asignado'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_rol_asignado'))
        batch_op.drop_index(batch_op.f('ix_user_correo_electronico'))
        batch_op.alter_column('rol_asignado',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('password',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('correo_electronico',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
        batch_op.alter_column('nombre_completo',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)

    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_user_id'))

    op.drop_table('customer')
    # ### end Alembic commands ###
