"""add 'Produccion' module

Revision ID: 98d9fdba92e1
Revises: b0eacff216e2
Create Date: 2026-04-04 12:39:53.364511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98d9fdba92e1'
down_revision = 'b0eacff216e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('production_task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('receta_id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('prioridad', sa.String(length=10), nullable=True),
    sa.Column('fecha_limite', sa.DateTime(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['receta_id'], ['recipe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('production_task')
    # ### end Alembic commands ###
