"""Added is_active to Merma for soft delete

Revision ID: b0eacff216e2
Revises: f98c3a150598
Create Date: 2026-04-04 11:53:50.217685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0eacff216e2'
down_revision = 'f98c3a150598'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('MERMA', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('MERMA', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
