"""add 'Mermas' module

Revision ID: f98c3a150598
Revises: 0d1d6acd4c50
Create Date: 2026-04-03 23:06:40.263511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f98c3a150598'
down_revision = '0d1d6acd4c50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('MERMA',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('insumo_id', sa.Integer(), nullable=True),
    sa.Column('cantidad_perdida', sa.Float(), nullable=False),
    sa.Column('causa', sa.String(length=255), nullable=True),
    sa.Column('notas_adicionales', sa.Text(), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['insumo_id'], ['INSUMO.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('MERMA')
    # ### end Alembic commands ###
